/**
 * ============================================================================
 * BRAINTREE DEMO SUITE — SERVER
 * ============================================================================
 *
 * WHY DOES THIS SERVER EXIST AT ALL?
 * -----------------------------------
 * Braintree's architecture is split into two trust zones, and this file is
 * the entire "server-side" half of that split:
 *
 *   1. SERVER-SIDE (this file) — holds the PRIVATE KEY. The private key can
 *      authorize real money movement (sales, refunds, voids). It must never
 *      be sent to a browser, embedded in frontend JS, or committed to a
 *      public repo. Every operation that touches the private key happens
 *      here, on infrastructure you control.
 *
 *   2. CLIENT-SIDE (everything in /public) — holds only a CLIENT TOKEN, a
 *      short-lived, scoped-down credential generated BY the server FOR one
 *      browser session. A client token can tokenize a payment method (turn
 *      a card/PayPal login/etc. into a one-time-use "nonce"), but it cannot
 *      move money on its own. This is what makes it safe to put in a browser.
 *
 * This client-token / nonce split is the single most important concept in
 * Braintree's integration model — nearly everything else in this codebase
 * exists to demonstrate it.
 * ============================================================================
 */

require('dotenv').config();
const express = require('express');
const cors = require('cors');
const braintree = require('braintree');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

const vaultedCustomers = [];

function buildGateway({ merchantId, publicKey, privateKey, environment } = {}) {
  const env = (environment || process.env.BT_ENVIRONMENT || 'Sandbox').toLowerCase() === 'production'
    ? braintree.Environment.Production
    : braintree.Environment.Sandbox;

  return new braintree.BraintreeGateway({
    environment: env,
    merchantId: merchantId || process.env.BT_MERCHANT_ID,
    publicKey: publicKey || process.env.BT_PUBLIC_KEY,
    privateKey: privateKey || process.env.BT_PRIVATE_KEY,
  });
}

app.post('/api/client-token', async (req, res) => {
  try {
    const gateway = buildGateway(req.body || {});
    const response = await gateway.clientToken.generate({});
    res.json({
      success: true,
      clientToken: response.clientToken,
      raw: response,
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});

// >>> STEP:checkout
app.post('/api/checkout', async (req, res) => {
  const { paymentMethodNonce, amount, credentials, customer, billingAddress, saveInVault } = req.body;

  if (!paymentMethodNonce || !amount) {
    return res.status(400).json({
      success: false,
      error: 'paymentMethodNonce and amount are required',
    });
  }

  try {
    const gateway = buildGateway(credentials || {});

    const saleRequest = {
      amount: String(amount),
      paymentMethodNonce,
      options: {
        submitForSettlement: true,
      },
    };

    if (customer && (customer.firstName || customer.lastName || customer.email)) {
      saleRequest.customer = {
        firstName: customer.firstName || undefined,
        lastName: customer.lastName || undefined,
        email: customer.email || undefined,
      };
    }

    if (billingAddress && billingAddress.streetAddress) {
      saleRequest.billing = {
        streetAddress: billingAddress.streetAddress || undefined,
        locality: billingAddress.locality || undefined,
        region: billingAddress.region || undefined,
        postalCode: billingAddress.postalCode || undefined,
        countryCodeAlpha2: billingAddress.countryCodeAlpha2 || undefined,
      };
    }

    if (saveInVault) {
      saleRequest.options.storeInVaultOnSuccess = true;
    }

    const result = await gateway.transaction.sale(saleRequest);

    if (result.success && saveInVault && result.transaction.customer && result.transaction.paymentMethodToken) {
      vaultedCustomers.push({
        customerId: result.transaction.customer.id,
        paymentMethodToken: result.transaction.paymentMethodToken,
        label: `${result.transaction.customer.firstName || ''} ${result.transaction.customer.lastName || ''}`.trim()
          || result.transaction.customer.email
          || result.transaction.customer.id,
        paymentInstrumentType: result.transaction.paymentInstrumentType,
        vaultedAt: new Date().toISOString(),
        source: 'checkout-with-vault',
      });
    }

    res.json({
      success: result.success,
      transaction: result.success ? result.transaction : null,
      message: result.message,
      raw: result,
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});
// <<< STEP:checkout


// >>> STEP:vaultstore
app.post('/api/vault/store', async (req, res) => {
  const { paymentMethodNonce, customer, credentials, usBankAccountVerificationMethod } = req.body;

  if (!paymentMethodNonce) {
    return res.status(400).json({
      success: false,
      error: 'paymentMethodNonce is required',
    });
  }

  try {
    const gateway = buildGateway(credentials || {});

    // ---------------------------------------------------------------------
    // Card vaulting (no verification method): customer.create() combined
    // with paymentMethodNonce in one call works fine — this is Braintree's
    // normal "create customer + attach payment method" shortcut.
    //
    // ACH vaulting (usBankAccountVerificationMethod present): that option
    // is ONLY valid on paymentMethod.create() with an existing customerId —
    // it is not a valid key inside customer.create(), even combined with a
    // nonce. Passing it there fails the same way options[usBankAccountVerificationMethod]
    // failed on transaction.sale() in /api/ach/charge. So for ACH we split
    // this into two calls: create a bare customer first, then vault +
    // verify the bank account against that customerId.
    // ---------------------------------------------------------------------
    let result;

    if (usBankAccountVerificationMethod) {
      const customerResult = await gateway.customer.create({
        firstName: customer?.firstName || undefined,
        lastName: customer?.lastName || undefined,
        email: customer?.email || undefined,
      });

      if (!customerResult.success) {
        return res.status(402).json({
          success: false,
          error: customerResult.message,
          raw: customerResult,
        });
      }

      const paymentMethodResult = await gateway.paymentMethod.create({
        customerId: customerResult.customer.id,
        paymentMethodNonce,
        options: {
          usBankAccountVerificationMethod,
        },
      });

      // Reshape to look like a customer.create() result below, so the rest
      // of this handler (and the frontend) doesn't need two code paths.
      result = {
        success: paymentMethodResult.success,
        message: paymentMethodResult.message,
        customer: paymentMethodResult.success
          ? { ...customerResult.customer, paymentMethods: [paymentMethodResult.paymentMethod] }
          : null,
        raw: { customerResult, paymentMethodResult },
      };
    } else {
      const customerRequest = {
        paymentMethodNonce,
      };
      if (customer && (customer.firstName || customer.lastName || customer.email)) {
        customerRequest.firstName = customer.firstName || undefined;
        customerRequest.lastName = customer.lastName || undefined;
        customerRequest.email = customer.email || undefined;
      }

      result = await gateway.customer.create(customerRequest);
    }

    if (result.success) {
      const paymentMethods = result.customer.paymentMethods || [];
      const primaryMethod = paymentMethods[0];

      vaultedCustomers.push({
        customerId: result.customer.id,
        paymentMethodToken: primaryMethod ? primaryMethod.token : null,
        label: `${result.customer.firstName || ''} ${result.customer.lastName || ''}`.trim()
          || result.customer.email
          || result.customer.id,
        paymentInstrumentType: primaryMethod ? primaryMethod.constructor?.name : 'unknown',
        vaultedAt: new Date().toISOString(),
        source: 'vault-store',
      });
    }

    res.json({
      success: result.success,
      customer: result.success ? result.customer : null,
      message: result.message,
      raw: result.raw || result,
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});
// <<< STEP:vaultstore

// >>> STEP:vaultcharge
app.post('/api/vault/charge', async (req, res) => {
  const { paymentMethodToken, amount, credentials } = req.body;

  if (!paymentMethodToken || !amount) {
    return res.status(400).json({
      success: false,
      error: 'paymentMethodToken and amount are required',
    });
  }

  try {
    const gateway = buildGateway(credentials || {});

    const result = await gateway.transaction.sale({
      amount: String(amount),
      paymentMethodToken,
      options: {
        submitForSettlement: true,
      },
    });

    res.json({
      success: result.success,
      transaction: result.success ? result.transaction : null,
      message: result.message,
      raw: result,
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});
// <<< STEP:vaultcharge

app.get('/api/vault/customers', (req, res) => {
  res.json({ success: true, customers: vaultedCustomers });
});

// ---------------------------------------------------------------------------
// POST /api/payouts/credit
// ---------------------------------------------------------------------------
// A DETACHED (BLIND) CREDIT — money moving FROM the merchant TO a vaulted
// payment method, with NO prior sale transaction to reference. Every other
// route in this file moves money customer → merchant (sale) or nothing at
// all (vault store). This is the only one that goes the other direction.
//
// This is NOT enabled by default on any Braintree account, sandbox or
// production. It requires:
//   1. "Credits Enabled" checked on the merchant account (internal gateway
//      admin toggle — not self-service in the Control Panel).
//   2. The specific Control Panel role issuing the credit has "Create
//      Credits without a Previous Transaction" permission enabled.
// Card network rules (Visa/Mastercard) generally prohibit sending funds to
// a card without a corresponding sale — this exists for narrow, reviewed
// use cases (refunding after a processor migration, gaming/RMG payouts
// under compliance agreements, etc.), not as a general payment path.
//
// gateway.transaction.credit() is a DEDICATED method — distinct from
// .sale() — mirroring it in shape (amount + paymentMethodToken) but moving
// money in the opposite direction. There is no "type: credit" flag on
// .sale() to watch out for here; the SDK gives you a separate method name
// specifically so this can't be triggered by accident.
// ---------------------------------------------------------------------------
// >>> STEP:payoutscredit
app.post('/api/payouts/credit', async (req, res) => {
  const { paymentMethodToken, amount, credentials } = req.body;

  if (!paymentMethodToken || !amount) {
    return res.status(400).json({
      success: false,
      error: 'paymentMethodToken and amount are required',
    });
  }

  try {
    const gateway = buildGateway(credentials || {});

    const result = await gateway.transaction.credit({
      amount: String(amount),
      paymentMethodToken,
    });

    res.json({
      success: result.success,
      transaction: result.success ? result.transaction : null,
      message: result.message,
      raw: result,
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});
// <<< STEP:payoutscredit

// ---------------------------------------------------------------------------
// POST /api/ach/charge
// ---------------------------------------------------------------------------
// ACH DOESN'T FOLLOW THE SAME ONE-CALL PATTERN AS CARD/PAYPAL/VENMO.
//
// Every other payment method in this demo takes a nonce straight into
// transaction.sale() and that's the whole story. ACH can't do that, because
// usBankAccountVerificationMethod is not a valid transaction.sale() option —
// Braintree only accepts it on paymentMethod.create(). Passing it to
// transaction.sale() (as this endpoint used to) fails immediately with:
//   invalidKeysError: "These keys are invalid: options[usBankAccountVerificationMethod]"
//
// The actual required flow is Braintree's "verify-then-charge" pattern, and
// it's genuinely two separate API calls:
//
//   1. paymentMethod.create() — vaults the bank account nonce AND runs the
//      requested verification (network check here). This step needs a
//      customerId, because ACH verification is tied to a customer record,
//      not a bare nonce. Returns a paymentMethodToken once vaulted.
//
//   2. transaction.sale() — charges that verified paymentMethodToken. No
//      verification option belongs here at all; verification already
//      happened in step 1.
//
// This is different from Card/PayPal, where a single transaction.sale() can
// tokenize-and-charge in one call — ACH's verification requirement forces
// the split.
// ---------------------------------------------------------------------------
// >>> STEP:achcharge
app.post('/api/ach/charge', async (req, res) => {
  const { paymentMethodNonce, amount, customer, credentials } = req.body;

  if (!paymentMethodNonce || !amount) {
    return res.status(400).json({
      success: false,
      error: 'paymentMethodNonce and amount are required',
    });
  }

  try {
    const gateway = buildGateway(credentials || {});

    // Step 0: ACH verification needs a customer record to attach to. Create
    // a lightweight one here rather than requiring the caller to manage
    // customer IDs — fine for a demo; a real integration would likely reuse
    // an existing logged-in customer's ID instead of minting a new one per
    // charge.
    const customerResult = await gateway.customer.create({
      firstName: customer?.firstName || undefined,
      lastName: customer?.lastName || undefined,
      email: customer?.email || undefined,
    });

    if (!customerResult.success) {
      return res.status(402).json({
        success: false,
        error: customerResult.message,
        raw: customerResult,
      });
    }

    // Step 1: Vault + verify the bank account. This is the ONLY place
    // usBankAccountVerificationMethod is a valid option.
    const paymentMethodResult = await gateway.paymentMethod.create({
      customerId: customerResult.customer.id,
      paymentMethodNonce,
      options: {
        usBankAccountVerificationMethod: 'network_check',
      },
    });

    if (!paymentMethodResult.success) {
      return res.status(402).json({
        success: false,
        error: paymentMethodResult.message,
        raw: paymentMethodResult,
      });
    }

    const verifiedToken = paymentMethodResult.usBankAccount?.token
      || paymentMethodResult.paymentMethod?.token;

    // Step 2: Charge the now-verified payment method. No verification
    // option here — that already happened in Step 1.
    const result = await gateway.transaction.sale({
      amount: String(amount),
      paymentMethodToken: verifiedToken,
      options: {
        submitForSettlement: true,
      },
    });

    res.json({
      success: result.success,
      transaction: result.success ? result.transaction : null,
      message: result.message,
      raw: { customerResult, paymentMethodResult, saleResult: result },
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      error: err.message,
      raw: err,
    });
  }
});
// <<< STEP:achcharge

// ---------------------------------------------------------------------------
// GET /api/_source/:filename
// ---------------------------------------------------------------------------
// Exists ONLY so the Code Panel (see /shared/code-panel.js) can show the
// real server.js alongside the real app.js when walking through a demo.
// app.js is already reachable via a normal static-file request; this route
// is the server-side equivalent, since a running server obviously isn't
// otherwise fetchable by a browser.
//
// Deliberately narrow: hardcoded to this exact file via __filename, not a
// user-suppliable path — this is a teaching/demo convenience, not something
// that should ever resemble a generic "read any file" endpoint.
// ---------------------------------------------------------------------------
app.get('/api/_source/server.js', (req, res) => {
  try {
    const source = fs.readFileSync(__filename, 'utf8');
    res.json({ success: true, code: source });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

const PORT = process.env.PORT || 3000;

// ---------------------------------------------------------------------------
// HTTPS instead of plain HTTP
// ---------------------------------------------------------------------------
// Apple Pay JS refuses to start a session from an insecure (http://) document
// — this throws InvalidAccessError at runtime, not at load time, which is
// why it can look like nothing is happening. A self-signed cert is enough
// to satisfy `window.isSecureContext`; Safari will show a one-time warning
// for the untrusted cert, but Apple Pay itself doesn't care that it's
// self-signed, only that the connection is HTTPS.
//
// The two cert files below are generated locally via:
//   openssl req -x509 -newkey rsa:2048 -nodes \
//     -keyout localhost-key.pem -out localhost-cert.pem \
//     -days 365 -subj "/CN=localhost"
// and should sit alongside this server.js file.
// ---------------------------------------------------------------------------
const https = require('https');
const fs = require('fs');

const httpsOptions = {
  key: fs.readFileSync(path.join(__dirname, 'localhost-key.pem')),
  cert: fs.readFileSync(path.join(__dirname, 'localhost-cert.pem')),
};

https.createServer(httpsOptions, app).listen(PORT, () => {
  console.log(`\nDemo suite running: https://localhost:${PORT}\n`);
});
